### ISSUE TITLE
Calling async function from sync function leads to surprising behavior

### ISSUE THREAD

**Issue by mika-fischer** [pcan/node-stomp-protocol#6]
https://github.com/pcan/node-stomp-protocol/blob/c807ab46c1fa9fe761f704792caf19cf0c7dfecb/src/session.ts#L40x

There are two problems with this:
1. The promise returned by the async function might be rejected leading to an unhandled rejection.
2. Depending on what the user code reacting to the received message does, it is possible that a later message overtakes the previous one. It might also be surprising that the handler can be called multiple times concurrently.

This behavior is unexpected for an async function. I think a better design would be to buffer the received messages and process them sequentially or to stop receiving more events from the socket while the current message is being processed and restart the socket when the handler is finished.

**Comment by pcan** [comment]
Good catch @mika-fischer! I think I'm going to update the code with your first suggestion (buffering). The second solution (`socket.pause()`) seems harder to implement, since `net.Socket` has `pause()` and `resume()`, but `WebSocket` handles it internally (see [here](https://github.com/websockets/ws/blob/a4050db3ad981db1c49daf5ba756ec4f4f71bc44/lib/websocket.js#L812) and [here](https://github.com/websockets/ws/blob/a4050db3ad981db1c49daf5ba756ec4f4f71bc44/lib/websocket.js#L707)), let me know if you have further suggestions about this one: having both mechanisms could give more flexibility (controlling socket back-pressure and buffering together).

**Comment by mika-fischer** [comment]
Yes, I agree that back-pressure is difficult with ws, I ran into that problem myself in the past... I think buffering is good enough for most use-cases. It would be good enough for my use-case anyway :-)

Thanks for publishing this library BTW, it'll be very useful!

**Comment by pcan** [comment]
I'm going to close this issue only for the first point. I'm opening another issue for the concurrency problem you reported, since in some cases it's still useful to have concurrent message processing in case of long running processes triggered by STOMP messages (serialization would be a bigger issue in that case). The improvement will include a boolean "switch" for the StompSession that enables serialized message processing through buffering.

**Comment by mika-fischer** [comment]
Yes, I agree that both use-cases are valid and important. Another way would be to just make the functions in `StompClientCommands` sync, i.e. don't accept a promise and leave the error handling and buffering to the user.

The way it is now, it's kind of implied in my opinion that if the API accepts an async function as a listener, then it will wait for the returned promise before calling the listener again, because why else would it even accept a promise in the first place? :-)

**Comment by pcan** [comment]
> The way it is now, it's kind of implied in my opinion that if the API accepts an async function as a listener, then it will wait for the returned promise before calling the listener again

Ok, now I got your point. It was not so clear to me in the beginning, but I think that you're right about the _ergonomics_ of the API, and I think this aspect is more important than serial/parallel message processing. I think I'll move to a sync API, since buffering/queuing can be handled by the user, furthermore this solution promotes a clean separation of  concerns.
Thanks again for your feedback!
